[package]
name = "fill-fake"
version = "0.1.0"
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
walkdir = "2"
postgres = "0.19.1"
clap = "2.33.3"
